name: Download Radverkehrsdaten

on:
  schedule:
    - cron: '30 5 * * *' # 5:30 UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ogr2ogr
        run: sudo apt install -y gdal-bin
      - name: Download
        run: mkdir -p dist/ && wget -O HH_WFS_DB_Rad_Plus.gml "https://geodienste.hamburg.de/HH_WFS_DB_Rad_Plus?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetFeature&typename=de.hh.up:aktuelles_jahr,de.hh.up:letzte_woche,de.hh.up:jahr2022"
      - name: Convert 2023
        run: ogr2ogr -f "GeoJSON" dist/dbrad2023.json  -s_srs EPSG:25832 -t_srs WGS84 -skipfailures HH_WFS_DB_Rad_Plus.gml aktuelles_jahr
      - name: Convert Letzte Woche
        run: ogr2ogr -f "GeoJSON" dist/dbrad2023_woche.json  -s_srs EPSG:25832 -t_srs WGS84 -skipfailures HH_WFS_DB_Rad_Plus.gml letzte_woche
      - name: Archive GeoJSON
        uses: actions/upload-artifact@v3
        with:
          name: dist-json
          path: |
            dist/*.json
